#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Licensed under the GNU LGPL v2.1 - http://www.gnu.org/licenses/lgpl.html

"""Corpus in Mallet format of List-Of-Words."""

from __future__ import with_statement

import logging

from gensim import utils
from gensim.corpora import LowCorpus


logger = logging.getLogger('gensim.corpora.malletcorpus')


class MalletCorpus(LowCorpus):
    """

    Notes
    -----
    Quoting http://mallet.cs.umass.edu/import.php:

        One file, one instance per line
        Assume the data is in the following format:

        [URL] [language] [text of the page...]

    Or, more generally,
        [document #1 id] [label] [text of the document...]
        [document #2 id] [label] [text of the document...]
        ...
        [document #N id] [label] [text of the document...]

    Note that language/label is *not* considered in Gensim.

    """
    def __init__(self, fname, id2word=None, metadata=False):
        """Initialize the corpus from a file.

        Parameters
        ----------
        fname : str
            File name.
        id2word : str, optional
            If provided, it is a dictionary mapping between word_ids (integers) and words (strings).
            Otherwise, the mapping is constructed from the documents.
        metadata : str, optional
            THIS PARAMETER WILL BE IGNORED.

        Attributes
        ----------
        metadata : str, optional
            THIS PARAMETER WILL BE IGNORED.

        Examples
        --------
        >>> from gensim.test.utils import datapath
        >>> from gensim.corpora import malletcorpus
        >>> data = malletcorpus.MalletCorpus(datapath("testcorpus.mallet"))
        >>> print data.id2word
        {0: u'computer', 1: u'eps', 2: u'graph', 3: u'human', 4: u'interface', 5: u'minors', 6: u'response',
        7: u'survey', 8: u'system', 9: u'time', 10: u'trees', 11: u'user'}


        """
        self.metadata = metadata
        LowCorpus.__init__(self, fname, id2word)

    def _calculate_num_docs(self):
        with utils.smart_open(self.fname) as fin:
            result = sum(1 for _ in fin)
        return result

    def __iter__(self):
        """Iterate over the corpus at the given filename.

        Notes
        -----
        Yields a bag-of-words, a.k.a list of tuples of (word id, word count), based on the given id2word dictionary.

        """
        with utils.smart_open(self.fname) as f:
            for line in f:
                yield self.line2doc(line)

    def line2doc(self, line):
        """Turn line into document.

        Parameters
        ----------
        line : str
            Line from input file.

        Return
        ------
        list of tuples
            Construct a list of (word, wordFrequency) 2-tuples.

        Examples
        --------
        >>> from gensim.test.utils import datapath
        >>> from gensim.corpora import malletcorpus
        >>> data = malletcorpus.MalletCorpus(datapath("testcorpus.mallet"))
        >>> docline = data.line2doc("en computer human interface")
        >>> print docline
        [(3, 1), (4, 1)]

        """
        splited_line = [word for word in utils.to_unicode(line).strip().split(' ') if word]
        docid, doclang, words = splited_line[0], splited_line[1], splited_line[2:]

        doc = super(MalletCorpus, self).line2doc(' '.join(words))

        if self.metadata:
            return doc, (docid, doclang)
        else:
            return doc

    @staticmethod
    def save_corpus(fname, corpus, id2word=None, metadata=False):
        """Save a corpus in the Mallet format.

        Notes
        -----
        The document id will be generated by enumerating the corpus.
        That is, it will range between 0 and number of documents in the corpus.

        Since Mallet has a language field in the format, this defaults to the string '__unknown__'.
        If the language needs to be saved, post-processing will be required.

        This function is automatically called by `MalletCorpus.serialize`; don't
        call it directly, call `serialize` instead.

        """
        if id2word is None:
            logger.info("no word id mapping provided; initializing from corpus")
            id2word = utils.dict_from_corpus(corpus)

        logger.info("storing corpus in Mallet format into %s", fname)

        truncated = 0
        offsets = []
        with utils.smart_open(fname, 'wb') as fout:
            for doc_id, doc in enumerate(corpus):
                if metadata:
                    doc_id, doc_lang = doc[1]
                    doc = doc[0]
                else:
                    doc_lang = '__unknown__'

                words = []
                for wordid, value in doc:
                    if abs(int(value) - value) > 1e-6:
                        truncated += 1
                    words.extend([utils.to_unicode(id2word[wordid])] * int(value))
                offsets.append(fout.tell())
                fout.write(utils.to_utf8('%s %s %s\n' % (doc_id, doc_lang, ' '.join(words))))

        if truncated:
            logger.warning(
                "Mallet format can only save vectors with integer elements; "
                "%i float entries were truncated to integer value", truncated
            )

        return offsets

    def docbyoffset(self, offset):
        """Return the document stored at file position `offset`.

        Parameters
        ----------
        offset : int

        Return
        list of tuples
            Construct a list of (word, wordFrequency) 2-tuples.

        Examples
        --------
        >>> from gensim.test.utils import datapath
        >>> from gensim.corpora import malletcorpus
        >>> data = malletcorpus.MalletCorpus(datapath("testcorpus.mallet"))
        >>>
        >>> data.docbyoffset(0)
        >>>
        >>> #All words at the first line.
        [(0, 1), (3, 1), (4, 1)]
        >>>
        >>> data.docbyoffset(4)
        >>>
        >>> #Last word at the first line.
        [(4, 1)]
        >>>
        >>> data.docbyoffset(19)
        >>> #TODO something wrong with it
        >>>
        >>> #There are no docs at the end of the first line.
        >>> []


        """
        with utils.smart_open(self.fname) as f:
            f.seek(offset)
            return self.line2doc(f.readline())
