FROM python:3.6.0

MAINTAINER Daniel Baptista Dias <danielbpdias@gmail.com>

# Install dependencies
RUN pip3 install \
    cython \
    sklearn \
    pandas \
    matplotlib \
    nltk \
    pyemd \
    jupyter \
    gensim