name: Linters

on:
  workflow_call:
  
jobs:

  linters:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - name: Setup up Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Update pip
        run: python -m pip install -U pip

      - name: Install dependencies
        run: python -m pip install flake8 flake8-rst

      - name: Run flake8 linter (source)
        run: flake8 --ignore E12,W503 --max-line-length 120 --show-source gensim

      # - name: Run flake8 linter (documentation)
      #   run: flake8 --ignore E202,E402,E302,E305,F821 --max-line-length 120 --filename '*.py,*.rst' docs

      - name: Check Sphinx Gallery cache
        run: python docs/src/check_gallery.py
